ALTER TABLE albums ADD COLUMN record_id BIGINT;

CREATE SEQUENCE albums_record_id_seq;

UPDATE albums
SET record_id = nextval('albums_record_id_seq')
WHERE record_id IS NULL;

SELECT setval(
    'albums_record_id_seq',
    (SELECT max(record_id) FROM albums)
);

ALTER TABLE albums ALTER COLUMN record_id SET NOT NULL;

ALTER TABLE albums
ALTER COLUMN record_id
ADD GENERATED BY DEFAULT AS IDENTITY;