ALTER TABLE albums ADD COLUMN if not exists record_title_asc_id BIGINT;

CREATE SEQUENCE IF NOT EXISTS albums_record_title_asc_id_seq;

WITH ordered AS (
    SELECT
        albumid,
        nextval('albums_record_title_asc_id_seq') AS new_id
    FROM albums
    WHERE record_title_asc_id IS NULL
    ORDER BY title ASC
)
UPDATE albums
SET record_title_asc_id = ordered.new_id
FROM ordered
WHERE albums.albumid = ordered.albumid;

SELECT setval(
    'albums_record_title_asc_id_seq',
    (SELECT max(record_title_asc_id) FROM albums)
);

ALTER TABLE albums ALTER COLUMN record_title_asc_id SET NOT NULL;

ALTER TABLE albums
ALTER COLUMN record_title_asc_id
ADD GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX if not exists idx_albums_record_title_asc_id ON public.albums USING btree (record_title_asc_id);