alter table sonicserver_user add column if not exists DeletedAt timestamp default null;
alter table sonicserver_user add column if not exists IsDeleted bool default false not null;
alter table sonicserver_user add column if not exists LdapAuthenticated bool default true not null;
alter table sonicserver_user add column if not exists AdminRole bool default true not null;
alter table sonicserver_user add column if not exists SettingsRole bool default true not null;
alter table sonicserver_user add column if not exists StreamRole bool default true not null;
alter table sonicserver_user add column if not exists JukeboxRole bool default true not null;
alter table sonicserver_user add column if not exists DownloadRole bool default true not null;
alter table sonicserver_user add column if not exists UploadRole bool default true not null;
alter table sonicserver_user add column if not exists CoverArtRole bool default true not null;
alter table sonicserver_user add column if not exists CommentRole bool default true not null;
alter table sonicserver_user add column if not exists PodcastRole bool default true not null;
alter table sonicserver_user add column if not exists ShareRole bool default true not null;
alter table sonicserver_user add column if not exists VideoConversionRole bool default true not null;
alter table sonicserver_user add column if not exists MusicFolderId int default 1 not null;
alter table sonicserver_user add column if not exists MaxBitRate int default 0 not null;
alter table sonicserver_user add column if not exists UpdatedAt timestamp default current_timestamp not null;
