ALTER TABLE artists ADD COLUMN record_id BIGINT;

CREATE SEQUENCE artists_record_id_seq;

UPDATE artists
SET record_id = nextval('artists_record_id_seq')
WHERE record_id IS NULL;

SELECT setval(
    'artists_record_id_seq',
    (SELECT max(record_id) FROM artists)
);

ALTER TABLE artists ALTER COLUMN record_id SET NOT NULL;

ALTER TABLE artists
ALTER COLUMN record_id
ADD GENERATED BY DEFAULT AS IDENTITY;