ALTER TABLE metadata ADD COLUMN record_id BIGINT;

CREATE SEQUENCE IF NOT EXISTS metadata_record_id_seq;

UPDATE metadata
SET record_id = nextval('metadata_record_id_seq')
WHERE record_id IS NULL;

SELECT setval(
    'metadata_record_id_seq',
    (SELECT max(record_id) FROM metadata)
);

ALTER TABLE metadata ALTER COLUMN record_id SET NOT NULL;

ALTER TABLE metadata
ALTER COLUMN record_id
ADD GENERATED BY DEFAULT AS IDENTITY;